<div style="background-color:#17241B; border:1px solid #4F6F52; border-left:8px solid #7FA66A; padding:24px 28px; border-radius:16px; box-shadow:0 7px 20px rgba(0,0,0,0.28);">

<div style="color:#9BBF87; font-size:14px; letter-spacing:2px; margin-bottom:8px;">
🌿 AI & ML COURSE WITH BINX
</div>

<h1 style="color:#E8F0DF; font-family:Georgia,serif; font-size:32px; line-height:1.35; margin:0; padding-bottom:12px; border-bottom:2px solid #4F6F52;">
Week 1 — Day 4
</h1>

<h2 style="color:#B8D49F; font-size:22px; font-weight:normal; margin:12px 0 0 0;">
🐼 Pandas: Tabular Data
</h2>

<p style="color:#AFC0AE; font-size:14px; margin:8px 0 0 0;">
📊 Working with structured data • 🌍 CO₂ emissions • 🔎 Data exploration
</p>

</div>

<div style="background-color:#13251C; border:1px solid #3F6F4A; border-left:7px solid #6FAF78; padding:22px 24px; border-radius:15px; box-shadow:0 6px 18px rgba(0,0,0,0.25);">

<h2 style="color:#B7DDBB; font-family:Georgia,serif; font-size:25px; margin:0 0 8px 0; letter-spacing:0.3px;">
🌿 About the Dataset
</h2>

<p style="color:#7FAF88; font-size:14px; margin:0 0 20px 0;">
🌍 Global CO₂ Emissions • 📅 Yearly Records • 🌱 Environmental Data
</p>

<div style="background-color:#1A3023; padding:15px 18px; border-radius:10px; margin-bottom:12px; border-left:3px solid #6FAF78;">

<h3 style="color:#A8D5AE; font-size:18px; margin:0 0 7px 0;">
🍃 What is this dataset?
</h3>

<p style="color:#D5E8D8; font-size:15px; line-height:1.7; margin:0;">
This notebook uses a global dataset of CO₂ emissions collected across different years.
It includes both individual countries and aggregated regions.
</p>

</div>

<div style="display:flex; gap:12px; flex-wrap:wrap;">

<div style="background-color:#1A3023; padding:14px 16px; border-radius:10px; flex:1; min-width:180px;">

<h3 style="color:#A8D5AE; font-size:17px; margin:0 0 7px 0;">
🌱 Coverage
</h3>

<p style="color:#C9DEC9; font-size:14px; line-height:1.6; margin:0;">
Countries and regions such as <b>World</b>, <b>High income</b>, and <b>OECD members</b>.
</p>

</div>

<div style="background-color:#1A3023; padding:14px 16px; border-radius:10px; flex:1; min-width:180px;">

<h3 style="color:#A8D5AE; font-size:17px; margin:0 0 7px 0;">
♻️ Main Information
</h3>

<p style="color:#C9DEC9; font-size:14px; line-height:1.6; margin:0;">
Each record contains a country or region, its code, the year, and the recorded CO₂ emission value.
</p>

</div>

</div>

</div>

<div style="background-color:#1B2A20; border:1px solid #4F6F52; border-left:5px solid #7FA66A; padding:18px 22px; border-radius:12px; box-shadow:0 4px 14px rgba(0,0,0,0.22);">

<div style="color:#8FB37A; font-size:13px; letter-spacing:1.5px; margin-bottom:5px;">
🐼 PANDAS BASICS
</div>

<h2 style="color:#E3EDD9; font-family:Georgia,serif; font-size:24px; margin:0;">
4.1 Series and DataFrames
</h2>

<p style="color:#B8CBB5; font-size:15px; line-height:1.7; margin:9px 0 0 0;">
📊 A quick example showing the difference between a <b>Series</b> and a <b>DataFrame</b>.
</p>

</div>

In [17]:
import pandas as pd

# Series: single labeled column
series = pd.Series([1, 2, 3], name="Example")
print("\033[94mSeries:\033[0m")
print(series)
print("\033[92mType:\033[0m", type(series))

# DataFrame: full table (columns and rows)
dataframe = pd.DataFrame({"even": [2, 4, 6], "odd": [1, 3, 5]})
print("\n\033[94mDataFrame:\033[0m")
print(dataframe)
print("\033[92mType:\033[0m", type(dataframe))

Series:
0    1
1    2
2    3
Name: Example, dtype: int64
Type: <class 'pandas.Series'>

DataFrame:
   even  odd
0     2    1
1     4    3
2     6    5
Type: <class 'pandas.DataFrame'>

<div style="background-color:#1B2A20; border:1px solid #4F6F52; border-left:5px solid #7FA66A; padding:18px 22px; border-radius:12px; box-shadow:0 4px 14px rgba(0,0,0,0.22);">

<div style="color:#8FB37A; font-size:13px; letter-spacing:1.5px; margin-bottom:5px;">
🌱 DATA EXPLORATION
</div>

<h2 style="color:#E3EDD9; font-family:Georgia,serif; font-size:24px; margin:0;">
4.2 Loading and Inspecting Data
</h2>

<div style="height:2px; width:55px; background-color:#7FA66A; margin:10px 0;"></div>

<p style="color:#B8CBB5; font-size:15px; line-height:1.8; margin:0;">
🔍 Before working with a dataset, the first step is to <b>load it</b> and
take a quick look at its structure.
</p>

<p style="color:#A8BDA8; font-size:14px; line-height:1.7; margin:8px 0 0 0;">
📐 Check its shape &nbsp;•&nbsp; 🏷️ Explore its columns &nbsp;•&nbsp; 👀 Preview the actual rows
</p>

</div>

In [18]:
import pandas as pd

df = pd.read_csv("co2_emissions_data.csv")

df.head().style.set_table_styles([
    {
        'selector': 'th',
        'props': [
            ('background-color', '#4F6F52'),
            ('color', '#F1F7EC'),
            ('padding', '9px'),
            ('border', '1px solid #7FA66A'),
            ('font-weight', 'bold')
        ]
    },
    {
        'selector': 'td',
        'props': [
            ('background-color', '#1B2A20'),
            ('color', '#DDE8D6'),
            ('padding', '9px'),
            ('border', '1px solid #4F6F52')
        ]
    }
])

In [19]:
print("\033[94mShape:\033[0m", df.shape)

Shape: (13953, 4)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13953 entries, 0 to 13952
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_code  13953 non-null  str
 1   country_name  13953 non-null  str
 2   year          13953 non-null  int64
 3   value         13953 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 436.2 KB

In [21]:
df.describe()

               year         value
count  13953.000000  1.395300e+04
mean    1990.732316  8.254983e+05
std       17.187585  2.788923e+06
min     1960.000000 -8.067400e+01
25%     1976.000000  1.100000e+03
50%     1992.000000  1.390000e+04
75%     2006.000000  1.642779e+05
max     2019.000000  3.434401e+07

<div style="background-color:#1B2A20; border:1px solid #4F6F52; border-left:5px solid #7FA66A; padding:18px 22px; border-radius:12px; box-shadow:0 4px 14px rgba(0,0,0,0.22);">

<div style="color:#8FB37A; font-size:13px; letter-spacing:1.5px; margin-bottom:5px;">
🔎 DATA FILTERING
</div>

<h2 style="color:#E3EDD9; font-family:Georgia,serif; font-size:24px; margin:0;">
4.3 Selecting and Filtering
</h2>

<div style="height:2px; width:55px; background-color:#7FA66A; margin-top:10px;"></div>

</div>

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🌱 Select Single Columns
</h3>

In [22]:
df.columns

Index(['country_code', 'country_name', 'year', 'value'], dtype='str')

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🍃 Select Multiple Columns
</h3>

In [23]:
df[["country_code", "country_name", "value"]]

      country_code country_name         value
0              ABW        Aruba  11092.675000
1              ABW        Aruba  11576.719000
2              ABW        Aruba  12713.489000
3              ABW        Aruba  12178.107000
4              ABW        Aruba  11840.743000
...            ...          ...           ...
13948          ZWE     Zimbabwe  12430.000305
13949          ZWE     Zimbabwe  11020.000458
13950          ZWE     Zimbabwe  10340.000153
13951          ZWE     Zimbabwe  12380.000114
13952          ZWE     Zimbabwe  11760.000229

[13953 rows x 3 columns]

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
📏 Check the Range of <code style="color:#9BBF87;">value</code> First to Choose a Logical Threshold
</h3>

In [24]:
df["value"].describe

<bound method NDFrame.describe of 0        11092.675000
1        11576.719000
2        12713.489000
3        12178.107000
4        11840.743000
             ...
13948    12430.000305
13949    11020.000458
13950    10340.000153
13951    12380.000114
13952    11760.000229
Name: value, Length: 13953, dtype: float64>

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🌿 Boolean Filtering — Rows Where <code style="color:#9BBF87;">value</code> Is Above the Mean
</h3>

In [25]:
threshold = df["value"].mean()
df[df["value"] > threshold]

      country_code country_name  year         value
423            ARB   Arab World  1996  8.436291e+05
424            ARB   Arab World  1997  8.847770e+05
425            ARB   Arab World  1998  8.897156e+05
426            ARB   Arab World  1999  9.016245e+05
427            ARB   Arab World  2000  9.391917e+05
...            ...          ...   ...           ...
13647          WLD        World  2015  3.299554e+07
13648          WLD        World  2016  3.301856e+07
13649          WLD        World  2017  3.351454e+07
13650          WLD        World  2018  3.428935e+07
13651          WLD        World  2019  3.434401e+07

[1727 rows x 4 columns]

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🍃 Using <code style="color:#9BBF87;">.loc</code> — Select Country Name & Year for Rows Above the Threshold
</h3>

In [26]:
df.loc[df["value"]>threshold, ["country_name","year"]]

      country_name  year
423     Arab World  1996
424     Arab World  1997
425     Arab World  1998
426     Arab World  1999
427     Arab World  2000
...            ...   ...
13647        World  2015
13648        World  2016
13649        World  2017
13650        World  2018
13651        World  2019

[1727 rows x 2 columns]

<div style="background-color:#1B2A20; border:1px solid #4F6F52; border-left:5px solid #7FA66A; padding:18px 22px; border-radius:12px; box-shadow:0 4px 14px rgba(0,0,0,0.22);">

<div style="color:#8FB37A; font-size:13px; letter-spacing:1.5px; margin-bottom:5px;">
🧹 DATA CLEANING
</div>

<h2 style="color:#E3EDD9; font-family:Georgia,serif; font-size:24px; margin:0;">
4.4 Cleaning Data
</h2>

<div style="height:2px; width:55px; background-color:#7FA66A; margin:10px 0;"></div>

<p style="color:#B8CBB5; font-size:15px; line-height:1.8; margin:0;">
🌱 Real-world data is rarely perfect. Before analysis, we need to check for
<b>missing values</b>, <b>duplicates</b>, and <b>incorrect data types</b>.
</p>

<p style="color:#A8BDA8; font-size:14px; line-height:1.7; margin:9px 0 0 0;">
🔍 Inspect &nbsp;•&nbsp; 🧹 Clean &nbsp;•&nbsp; 🌿 Prepare &nbsp;•&nbsp; 📊 Analyze
</p>

</div>

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🔍 Count Missing Values per Column
</h3>

In [27]:
print("\033[94mMissing values per column:\033[0m")
df.isnull().sum()

Missing values per column:

country_code    0
country_name    0
year            0
value           0
dtype: int64

In [28]:
missing_count = df["value"].isnull().sum()
print("\033[93mMissing values in 'value' column:\033[0m", missing_count)

df["value"] = df["value"].fillna(df["value"].mean())
print("\033[92mFilled missing values with the mean.\033[0m")

Missing values in 'value' column: 0
Filled missing values with the mean.

In [29]:
print("Number of duplicate rows :", df.duplicated().sum())

Number of duplicate rows : 0

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
♻️ Remove Duplicates if Any Exist
</h3>

In [30]:
df.drop_duplicates(inplace=True)
print("Dataset after remove duplicates - Shape-",df.shape)

Dataset after remove duplicates - Shape- (13953, 4)

<div style="background-color:#1B2A20; border:1px solid #4F6F52; border-left:5px solid #7FA66A; padding:18px 22px; border-radius:12px; box-shadow:0 4px 14px rgba(0,0,0,0.22);">

<div style="color:#8FB37A; font-size:13px; letter-spacing:1.5px; margin-bottom:5px;">
🌿 DATA AGGREGATION
</div>

<h2 style="color:#E3EDD9; font-family:Georgia,serif; font-size:24px; margin:0;">
4.5 Grouping and Aggregation
</h2>

<div style="height:2px; width:55px; background-color:#7FA66A; margin:10px 0;"></div>

<p style="color:#B8CBB5; font-size:15px; line-height:1.8; margin:0;">
🌍 Group the data by <b>country</b> and calculate the <b>average CO₂ value</b> for each one.
</p>

<p style="color:#A8BDA8; font-size:14px; margin:9px 0 0 0;">
📊 Group &nbsp;→&nbsp; 🧮 Calculate Average &nbsp;→&nbsp; 🌱 Compare Countries
</p>

</div>

In [31]:
print("\033[94mAverage CO2 value per country:\033[0m")
df.groupby("country_name")["value"].mean()

Average CO2 value per country:

country_name
Afghanistan                    2.505611e+03
Africa Eastern and Southern    3.463568e+05
Africa Western and Central     1.075567e+05
Albania                        4.413947e+03
Algeria                        7.031805e+04
                                   ...
West Bank and Gaza             1.754320e+03
World                          2.195928e+07
Yemen, Rep.                    8.619050e+03
Zambia                         3.369701e+03
Zimbabwe                       1.116555e+04
Name: value, Length: 256, dtype: float64

<h3 style="color:#B8D49F; font-family:Georgia,serif; font-size:20px; text-shadow:0 0 5px rgba(127,166,106,0.25); margin:0; letter-spacing:0.3px;">
🌿 Multiple Aggregations per Country — Mean &amp; Maximum CO₂ Value
</h3>

In [32]:
print("\033[92mMean and max value per country:\033[0m")
df.groupby("country_name")["value"].agg(["mean", "max"])

Mean and max value per country:

                                     mean           max
country_name
Afghanistan                  2.505611e+03  8.930000e+03
Africa Eastern and Southern  3.463568e+05  6.030300e+05
Africa Western and Central   1.075567e+05  2.207400e+05
Albania                      4.413947e+03  8.984150e+03
Algeria                      7.031805e+04  1.712500e+05
...                                   ...           ...
West Bank and Gaza           1.754320e+03  3.234294e+03
World                        2.195928e+07  3.434401e+07
Yemen, Rep.                  8.619050e+03  2.783000e+04
Zambia                       3.369701e+03  7.730000e+03
Zimbabwe                     1.116555e+04  1.847000e+04

[256 rows x 2 columns]